version: '3.1'
 
services:

  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/root/'
    command: 'tail -f /dev/null'
    volumes:
      - ./app:/root/app
      - ./json:/root/json
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""